name:                cardano-addresses
version:             1.0.0
github:              input-output-hk/cardano-addresses
license:             Apache-2.0
author:              IOHK
maintainer:          operations@iohk.io
copyright:           2020 IOHK
synopsis:            Library utilities for mnemonic generation and address derivation.
category:            Cardano

description: |
  Please see the README on GitHub at <https://github.com/input-output-hk/cardano-addresses>

dependencies:
- base >= 4.7 && < 5

flags:
  release:
    description: Compile executables for a release.
    default: False
    manual: True

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wcompat
  - -fwarn-redundant-constraints
  when:
  - condition: flag(release)
    ghc-options:
    - -Werror
  default-extensions:
  - NoImplicitPrelude
  dependencies:
  - ansi-terminal
  - base58-bytestring
  - basement
  - bech32
  - bech32-th
  - binary
  - bytestring
  - cardano-crypto
  - cborg
  - cryptonite
  - deepseq
  - digest
  - exceptions
  - extra
  - fmt
  - memory
  - optparse-applicative
  - safe
  - text
  - template-haskell

executables:
  cardano-address:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -Wall
    - -Wcompat
    - -fwarn-redundant-constraints
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ansi-terminal
    - bech32
    - bech32-th
    - base58-bytestring
    - bytestring
    - cardano-addresses
    - cborg
    - extra
    - memory
    - optparse-applicative
    - safe
    - text
    when:
    - condition: flag(release)
      ghc-options:
      - -Werror
      - -static
      - -O2
      cc-options: -static
      ld-options: -static -pthread

tests:
  unit:
    source-dirs: test
    main: Main.hs
    default-extensions:
    - NoImplicitPrelude
    ghc-options:
    - -Wall
    - -Wcompat
    - -fwarn-redundant-constraints
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    when:
    - condition: flag(release)
      ghc-options:
      - -Werror
    dependencies:
    - bytestring
    - bech32
    - cardano-addresses
    - cardano-crypto
    - hspec
    - memory
    - QuickCheck
    - text
