resolver: lts-14.25

# Generate files required by Weeder.
# See https://github.com/ndmitchell/weeder/issues/53
ghc-options: {"$locals": -ddump-to-file -ddump-hi}

packages:
- .

extra-deps:
- base58-bytestring-0.1.0
- bech32-1.0.2
- bech32-th-1.0.2

- git: https://github.com/input-output-hk/cardano-crypto
  commit: 2547ad1e80aeabca2899951601079408becbc92c
